import type { AppChildRoute } from './routeTypes';

export const TENANT_APP_ROUTES: AppChildRoute[] = [
  { kind: 'redirect', index: true, to: '/dashboard' },
  {
    kind: 'page',
    path: 'dashboard',
    title: 'Dashboard',
    tenantPath: '/dashboard',
    load: () => import('../modules/dashboard/Dashboard'),
  },
  {
    kind: 'page',
    path: 'insights',
    title: 'Insights',
    tenantPath: '/insights',
    load: () => import('../modules/insights/AnalyticsPage'),
  },
  {
    kind: 'page',
    path: 'attendance',
    title: 'Attendance',
    tenantPath: '/attendance',
    load: () => import('../modules/attendance/AttendancePage'),
  },
  {
    kind: 'page',
    path: 'timesheet',
    title: 'Timesheet',
    tenantPath: '/timesheet',
    load: () => import('../modules/timesheet/TimesheetPage'),
  },
  {
    kind: 'page',
    path: 'leave/holidays',
    title: 'Company holidays',
    tenantPath: '/leave/holidays',
    load: () => import('../modules/leave/LeaveHolidaysPage'),
  },
  {
    kind: 'page',
    path: 'leave/team-calendar',
    title: 'Team leave calendar',
    tenantPath: '/leave/team-calendar',
    load: () => import('../modules/leave/LeaveTeamCalendarPage'),
  },
  {
    kind: 'page',
    path: 'leave',
    title: 'Leave',
    tenantPath: '/leave',
    load: () => import('../modules/leave/LeavePage'),
  },
  { kind: 'redirect', path: 'payroll', to: '/payroll/payslips' },
  {
    kind: 'page',
    path: 'payroll/payslips',
    title: 'Payslips and tax',
    payrollCapability: 'route.payroll.payslips',
    load: () => import('../modules/payroll/PayrollPayPage'),
  },
  {
    kind: 'page',
    path: 'payroll/pay',
    title: 'Payroll processing',
    payrollCapability: 'route.payroll.pay',
    load: () => import('../modules/payroll/PayrollPage'),
  },
  {
    kind: 'page',
    path: 'payroll/tax',
    title: 'Tax administration',
    payrollCapability: 'route.payroll.tax',
    load: () => import('../modules/payroll/PayrollTaxPage'),
  },
  {
    kind: 'page',
    path: 'payroll/compensation',
    title: 'Compensation setup',
    payrollCapability: 'route.payroll.compensation',
    load: () => import('../modules/payroll/PayrollCompensationPage'),
  },
  {
    kind: 'page',
    path: 'expenses',
    title: 'Expenses',
    tenantPath: '/expenses',
    load: () => import('../modules/expenses/ExpensesPage'),
  },
  {
    kind: 'page',
    path: 'notifications',
    title: 'Notifications',
    tenantPath: '/notifications',
    load: () => import('../modules/notifications/NotificationsPage'),
  },
  {
    kind: 'page',
    path: 'profile/settings',
    title: 'Profile and settings',
    tenantPath: '/profile/settings',
    load: () => import('../modules/profile/ProfileSettingsPage'),
  },
  {
    kind: 'page',
    path: 'organization/employees',
    title: 'Organization people',
    tenantPath: '/organization/employees',
    load: () => import('../modules/organization/OrganizationEmployeesPage'),
  },
  {
    kind: 'page',
    path: 'organization/employees/:employeeId',
    title: 'Employee details',
    tenantPath: '/organization/employees',
    load: () => import('../modules/organization/EmployeeDetailPage'),
  },
  {
    kind: 'page',
    path: 'organization/org-chart',
    title: 'Organization chart',
    tenantPath: '/organization/org-chart',
    load: () => import('../modules/organization/OrgChartPage'),
  },
  {
    kind: 'page',
    path: 'organization/documents',
    title: 'Organization documents',
    tenantPath: '/organization/documents',
    load: () => import('../modules/organization/OrganizationDocumentsPage'),
  },
  {
    kind: 'page',
    path: 'organization/profile-reviews',
    title: 'Profile reviews',
    tenantPath: '/organization/profile-reviews',
    load: () => import('../modules/organization/ProfileReviewPage'),
  },
  {
    kind: 'page',
    path: 'workplace/benefits',
    title: 'Benefits',
    tenantPath: '/workplace/benefits',
    load: () => import('../modules/workplace/BenefitsPage'),
  },
  {
    kind: 'page',
    path: 'workplace/recruitment',
    title: 'Recruitment',
    tenantPath: '/workplace/recruitment',
    load: () => import('../modules/workplace/RecruitmentPage'),
  },
  {
    kind: 'page',
    path: 'workplace/onboarding',
    title: 'Onboarding and exit',
    tenantPath: '/workplace/onboarding',
    load: () => import('../modules/workplace/OnboardingPage'),
  },
  {
    kind: 'page',
    path: 'workplace/performance',
    title: 'Performance',
    tenantPath: '/workplace/performance',
    load: () => import('../modules/workplace/PerformancePage'),
  },
  {
    kind: 'page',
    path: 'workplace/succession',
    title: 'Succession planning',
    tenantPath: '/workplace/succession',
    load: () => import('../modules/workplace/SuccessionPage'),
  },
  {
    kind: 'page',
    path: 'workplace/compensation',
    title: 'Compensation',
    tenantPath: '/workplace/compensation',
    load: () => import('../modules/workplace/CompensationPage'),
  },
  {
    kind: 'page',
    path: 'workplace/learning',
    title: 'Learning',
    tenantPath: '/workplace/learning',
    load: () => import('../modules/workplace/LearningPage'),
  },
  {
    kind: 'page',
    path: 'workplace/assets',
    title: 'Assets',
    tenantPath: '/workplace/assets',
    load: () => import('../modules/workplace/AssetsPage'),
  },
  {
    kind: 'page',
    path: 'workplace/grievance',
    title: 'Grievance and speak up',
    tenantPath: '/workplace/grievance',
    load: () => import('../modules/workplace/GrievancePage'),
  },
  {
    kind: 'page',
    path: 'workplace/workflows',
    title: 'Workflows',
    tenantPath: '/workplace/workflows',
    load: () => import('../modules/admin/AdminWorkflowsPage'),
  },
  {
    kind: 'page',
    path: 'hr',
    title: 'HR workbench',
    tenantPath: '/hr',
    load: () => import('../modules/hr/HrHomePage'),
  },
  {
    kind: 'page',
    path: 'hr/people',
    title: 'HR people',
    tenantPath: '/hr/people',
    load: () => import('../modules/admin/AdminEmployeesPage'),
  },
  {
    kind: 'page',
    path: 'hr/leaves',
    title: 'Leave approvals',
    tenantPath: '/hr/leaves',
    load: () => import('../modules/hr/HrLeavesPage'),
  },
  {
    kind: 'page',
    path: 'hr/attendance',
    title: 'Attendance management',
    tenantPath: '/hr/attendance',
    load: () => import('../modules/hr/HrAttendanceManagementPage'),
  },
  {
    kind: 'page',
    path: 'hr/timesheets',
    title: 'Timesheet approvals',
    tenantPath: '/hr/timesheets',
    load: () => import('../modules/hr/HrTimesheetsPage'),
  },
  {
    kind: 'page',
    path: 'hr/timesheet-assignments',
    title: 'Timesheet project access',
    tenantPath: '/hr/timesheet-assignments',
    load: () => import('../modules/hr/HrTimesheetProjectAssignmentsPage'),
  },
  {
    kind: 'redirect',
    path: 'hr/leave-settings',
    to: '/admin/leave-settings',
    tenantPath: '/admin/leave-settings',
  },
  {
    kind: 'redirect',
    path: 'hr/access',
    to: '/admin/access',
    tenantPath: '/admin/access',
  },
  {
    kind: 'page',
    path: 'admin/leave-settings',
    title: 'Leave settings',
    tenantPath: '/admin/leave-settings',
    load: () => import('../modules/admin/AdminLeaveSettingsPage'),
  },
  {
    kind: 'page',
    path: 'admin/expense-categories',
    title: 'Expense categories',
    tenantPath: '/admin/expense-categories',
    load: () => import('../modules/admin/AdminExpenseCategoriesPage'),
  },
  {
    kind: 'page',
    path: 'admin/notifications',
    title: 'Notification administration',
    tenantPath: '/admin/notifications',
    load: () => import('../modules/admin/AdminNotificationsPage'),
  },
  {
    kind: 'page',
    path: 'admin/employees',
    title: 'Employee administration',
    tenantPath: '/admin/employees',
    load: () => import('../modules/admin/AdminEmployeesPage'),
  },
  {
    kind: 'page',
    path: 'admin/attendance-policy',
    title: 'Attendance policy',
    tenantPath: '/admin/attendance-policy',
    load: () => import('../modules/admin/AdminAttendancePolicyPage'),
  },
  {
    kind: 'page',
    path: 'admin/timesheet-settings',
    title: 'Timesheet settings',
    tenantPath: '/admin/timesheet-settings',
    load: () => import('../modules/admin/AdminHrTimesheetSettingsPage'),
  },
  {
    kind: 'page',
    path: 'admin/reports',
    title: 'Reports',
    tenantPath: '/admin/reports',
    load: () => import('../modules/admin/AdminReportsPage'),
  },
  {
    kind: 'page',
    path: 'admin/access',
    title: 'Roles and permissions',
    tenantPath: '/admin/access',
    load: () => import('../modules/hr/HrAccessManagementPage'),
  },
  {
    kind: 'page',
    path: 'admin/settings',
    title: 'Administration settings',
    tenantPath: '/admin/settings',
    load: () => import('../modules/admin/AdminSettingsPage'),
  },
  {
    kind: 'page',
    path: 'admin/module-health',
    title: 'Module health',
    tenantPath: '/admin/module-health',
    load: () => import('../modules/admin/ModuleHealth'),
  },
];
