import {
  LeaveHealthDocument,
  AttendanceHealthDocument,
  PayrollHealthDocument,
  TaxHealthDocument,
  BenefitsHealthDocument,
  ExpenseHealthDocument,
  RecruitmentHealthDocument,
  PerformanceHealthDocument,
  LmsHealthDocument,
  SuccessionHealthDocument,
  CompensationHealthDocument,
  AssetsHealthDocument,
  GrievanceHealthDocument,
  WorkflowHealthDocument,
  NotificationHealthDocument,
  AnalyticsHealthDocument,
  TenantsHealthDocument,
  BillingHealthDocument,
  OperatorHealthDocument,
} from '../../api/graphql/graphql';

import type { ProbeConfig } from './moduleHealthTypes';

export const MODULE_HEALTH_PROBES: ProbeConfig[] = [
  {
    key: 'leave',
    label: 'Leave',
    plane: 'client',
    query: LeaveHealthDocument,
    previewFields: ['leaveTypes'],
  },
  {
    key: 'attendance',
    label: 'Attendance',
    plane: 'client',
    query: AttendanceHealthDocument,
    previewFields: ['shifts'],
  },
  {
    key: 'payroll',
    label: 'Payroll',
    plane: 'client',
    query: PayrollHealthDocument,
    previewFields: ['salaryComponents'],
  },
  {
    key: 'tax',
    label: 'Tax',
    plane: 'client',
    query: TaxHealthDocument,
    previewFields: ['taxConfigurations'],
  },
  {
    key: 'benefits',
    label: 'Benefits',
    plane: 'client',
    query: BenefitsHealthDocument,
    previewFields: ['benefitTypes'],
  },
  {
    key: 'expense',
    label: 'Expense',
    plane: 'client',
    query: ExpenseHealthDocument,
    previewFields: ['expenseCategories'],
  },
  {
    key: 'recruitment',
    label: 'Recruitment',
    plane: 'client',
    query: RecruitmentHealthDocument,
    previewFields: ['jobPostings'],
  },
  {
    key: 'performance',
    label: 'Performance',
    plane: 'client',
    query: PerformanceHealthDocument,
    previewFields: ['reviewCycles'],
  },
  {
    key: 'lms',
    label: 'LMS',
    plane: 'client',
    query: LmsHealthDocument,
    previewFields: ['skills'],
  },
  {
    key: 'succession',
    label: 'Succession',
    plane: 'client',
    query: SuccessionHealthDocument,
    previewFields: ['competencies'],
  },
  {
    key: 'compensation',
    label: 'Compensation',
    plane: 'client',
    query: CompensationHealthDocument,
    previewFields: ['salaryBands'],
  },
  {
    key: 'assets',
    label: 'Assets',
    plane: 'client',
    query: AssetsHealthDocument,
    previewFields: ['assetCategories'],
  },
  {
    key: 'grievance',
    label: 'Grievance',
    plane: 'client',
    query: GrievanceHealthDocument,
    previewFields: ['grievanceCategories'],
  },
  {
    key: 'workflow',
    label: 'Workflow',
    plane: 'client',
    query: WorkflowHealthDocument,
    previewFields: ['workflows'],
  },
  {
    key: 'notification',
    label: 'Notifications',
    plane: 'client',
    query: NotificationHealthDocument,
    previewFields: ['announcements'],
  },
  {
    key: 'analytics',
    label: 'Analytics',
    plane: 'client',
    query: AnalyticsHealthDocument,
    previewFields: ['webhookDeliveryLogs'],
  },
  {
    key: 'tenant',
    label: 'Tenants (Ops)',
    plane: 'operator',
    query: TenantsHealthDocument,
    previewFields: ['tenants'],
  },
  {
    key: 'billing',
    label: 'Billing (Ops)',
    plane: 'operator',
    query: BillingHealthDocument,
    previewFields: ['invoices'],
  },
  {
    key: 'operator',
    label: 'Operators (Ops)',
    plane: 'operator',
    query: OperatorHealthDocument,
    previewFields: ['operatorUsers'],
  },
];
