export const UI_ACTION_TEXT = {
  add: 'Add',
  cancel: 'Cancel',
  cancelEdit: 'Cancel edit',
  create: 'Create',
  delete: 'Delete',
  edit: 'Edit',
  remove: 'Remove',
  save: 'Save',
  saveChanges: 'Save changes',
  submit: 'Submit',
  update: 'Update',
} as const;

export const UI_STATUS_TEXT = {
  creating: 'Creating…',
  deleting: 'Deleting…',
  downloading: 'Downloading…',
  loading: 'Loading…',
  publishing: 'Publishing…',
  removing: 'Removing…',
  saving: 'Saving…',
  submitting: 'Submitting…',
  uploading: 'Uploading…',
} as const;

export const UI_EMPTY_TEXT = {
  employees: 'No employees found',
  employeesWithPeriod: 'No employees found.',
  employeesMatchSearch: 'No employees match this search.',
  matches: 'No matches. Try other words.',
  matchesTryAnotherSearch: 'No matches. Try another search.',
  notifications: 'No notifications',
  records: 'No records found.',
  sidebarItems: 'No items match',
} as const;

export const UI_A11Y_TEXT = {
  closeModal: 'Close modal',
  closeSidebar: 'Close sidebar',
  commandPalette: 'Command palette',
  dismiss: 'Dismiss',
  dismissNotification: 'Dismiss notification',
  filterSidebarMenu: 'Filter sidebar menu',
  loading: 'Loading',
} as const;

export const UI_FEEDBACK_TEXT = {
  copied: 'Copied.',
  copyUnavailable: 'Copy is unavailable. Select the value and copy it manually.',
  unknownStatus: 'Unknown status',
  unavailable: 'Unavailable',
} as const;

export const UI_FORM_TEXT = {
  chooseAny: 'Choose…',
  chooseEmployee: 'Choose an employee…',
  chooseProject: 'Choose project',
  loadingOption: 'Loading…',
  noneOption: 'None',
  selectEmployeeOption: 'Select employee',
} as const;

export const UI_FIELD_LABELS = {
  dateOfJoining: 'Date of joining',
  employeeCode: 'Employee code',
  firstName: 'First name',
  lastName: 'Last name',
  reportingManager: 'Reporting manager',
} as const;

export const UI_PLACEHOLDER_TEXT = {
  employeeSearch: 'Search by employee code or name…',
  globalSearch: 'Search pages, people, tools…',
  sidebarFilter: 'Filter menu and pages…',
  uuidEntitySearch: 'Search…',
} as const;

export const NAV_LABELS = {
  admin: 'Admin',
  adminAttendancePolicy: 'Admin - Attendance Policy',
  adminEmployees: 'Admin - Employees',
  adminExpenseCategories: 'Admin - Expense Categories',
  adminLeaveSettings: 'Admin - Leave Settings',
  adminReports: 'Admin - Reports',
  adminRolesPermissions: 'Admin - Roles & Permissions',
  adminServiceHealth: 'Admin - Service Health',
  adminSettings: 'Admin - Settings',
  adminTimesheetSettings: 'Admin - Timesheet Settings',
  assets: 'Assets',
  attendance: 'Attendance',
  attendancePolicy: 'Attendance Policy',
  benefits: 'Benefits',
  compensation: 'Compensation',
  compensationSetup: 'Compensation Setup',
  dashboard: 'Dashboard',
  documents: 'Documents',
  employees: 'Employees',
  expenseCategories: 'Expense Categories',
  expenses: 'Expenses',
  expensesTravel: 'Expenses & Travel',
  grievance: 'Grievance',
  grievanceSpeakUp: 'Grievance & Speak Up',
  hr: 'HR',
  hrLeaveApprovals: 'HR - Leave Approvals',
  hrPeopleAdmin: 'HR - People Admin',
  hrTimesheetApprovals: 'HR - Timesheet Approvals',
  hrTimesheetProjectAccess: 'HR - Timesheet Project Access',
  hrWorkbench: 'HR - Workbench',
  incomeTaxSelf: 'Income Tax (Self)',
  insights: 'Insights',
  leave: 'Leave',
  leaveApprovals: 'Leave Approvals',
  leaveCompanyHolidays: 'Leave - Company Holidays',
  leaveSettings: 'Leave Settings',
  leaveTeamCalendar: 'Leave - Team Calendar',
  learning: 'Learning',
  notifications: 'Notifications',
  onboardingExit: 'Onboarding & Exit',
  organization: 'Organization',
  organizationDocuments: 'Organization - Documents',
  organizationOrgChart: 'Organization - Org Chart',
  organizationPeople: 'Organization - People',
  orgChart: 'Org Chart',
  overview: 'Overview',
  payCompensationSetup: 'Pay - Compensation Setup',
  payIncomeTaxSelf: 'Pay - Income Tax (Self)',
  payPayrollProcessing: 'Pay - Payroll Processing',
  payTaxAdmin: 'Pay - Tax Admin',
  payroll: 'Payroll',
  payrollProcessing: 'Payroll Processing',
  peopleAdmin: 'People Admin',
  performance: 'Performance',
  profileSettings: 'Profile & Settings',
  recruitment: 'Recruitment',
  reports: 'Reports',
  rolesPermissions: 'Roles & Permissions',
  serviceHealth: 'Service Health',
  settings: 'Settings',
  succession: 'Succession',
  taxAdmin: 'Tax Admin',
  timesheet: 'Timesheet',
  timesheetApprovals: 'Timesheet Approvals',
  timesheetProjectAccess: 'Timesheet Project Access',
  timesheetSettings: 'Timesheet Settings',
  workplace: 'Workplace',
  workflows: 'Workflows',
} as const;
