import Button from '../../components/common/Button';
import Card from '../../components/common/Card';
import type { HrInsights, HrReportKind } from '../reports/reportDocuments';

const DisplayBars = ({
  title,
  items,
  report,
  open,
}: {
  title: string;
  items: { label: string; value: number; text?: string }[];
  report: HrReportKind;
  open: (report: HrReportKind) => void;
}) => {
  const maximum = Math.max(1, ...items.map((item) => item.value));
  return (
    <Card title={title}>
      <div className="space-y-3">
        {items.map((item) => (
          <div
            key={item.label}
            title={`${item.label}: ${item.text ?? item.value}`}
            className="block w-full rounded-lg text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500"
          >
            <span className="mb-1 flex justify-between gap-3 text-sm">
              <span>{item.label}</span>
              <strong>{item.text ?? item.value.toLocaleString()}</strong>
            </span>
            <span className="block h-3 overflow-hidden rounded-full bg-surface-muted">
              <span
                className="block h-full rounded-full bg-primary-500 transition-[width]"
                style={{ width: `${(item.value / maximum) * 100}%` }}
              />
            </span>
          </div>
        ))}
      </div>
      <Button
        size="sm"
        variant="quiet"
        className="mt-3"
        aria-label={`View all ${title.toLowerCase()} records for selected period`}
        onClick={() => open(report)}
      >
        View all period records
      </Button>
      {items.length === 0 && (
        <p className="text-sm text-content-secondary">No records in this period.</p>
      )}
    </Card>
  );
};

const HrInsightCharts = ({
  data,
  open,
}: {
  data: HrInsights;
  open: (report: HrReportKind) => void;
}) => (
  <div className="grid items-start gap-4 lg:grid-cols-2">
    {data.onTimeDays !== null && (
      <DisplayBars
        title="Attendance punctuality"
        report="ATTENDANCE_PUNCTUALITY"
        open={open}
        items={[
          { label: 'On time', value: data.onTimeDays },
          ...(data.lateDays === null ? [] : [{ label: 'Late', value: data.lateDays }]),
          ...(data.unknownPunctualityDays === null
            ? []
            : [{ label: 'Unknown', value: data.unknownPunctualityDays }]),
        ]}
      />
    )}
    {data.monthlyPayroll !== null && (
      <DisplayBars
        title="Net salary generated by month"
        report="PAYROLL_REGISTER"
        open={open}
        items={data.monthlyPayroll.map((row) => ({
          label: row.month,
          value: Number(row.netSalaryGenerated),
          text: row.netSalaryGenerated,
        }))}
      />
    )}
    {data.joiners !== null && (
      <DisplayBars
        title="Employee movements"
        report="EMPLOYEE_MOVEMENTS"
        open={open}
        items={[
          { label: 'Joined', value: data.joiners },
          ...(data.exits === null ? [] : [{ label: 'Exited', value: data.exits }]),
        ]}
      />
    )}
  </div>
);
export default HrInsightCharts;
