import type { User, UserProfileFull } from '../types';

export const getDefaultUserProfile = (user: User, companyName: string): UserProfileFull => ({
  userId: user.id,
  header: {
    email: user.email,
    phone: '',
    companyName,
    employeeId: user.employeeId,
  },
  org: {
    businessUnit: '-',
    department: user.department,
    reportingManager: '-',
  },
  primaryDetails: {
    name: user.name,
    displayName: user.name.split(' ')[0],
    gender: '-',
    maritalStatus: '-',
    dateOfBirth: '-',
    nationality: '-',
    physicallyHandicapped: false,
  },
  identification: {},
  addresses: [],
  contact: { phone: '' },
  education: [],
  pastExperience: [],
  timeline: [],
  jobDetail: {
    jobTitlePrimary: user.designation,
    managerName: '-',
    employeeId: user.employeeId,
    joiningDate: user.joiningDate,
    workerType: '-',
    timeType: 'full',
  },
  employeeTime: {
    shift: '-',
    weeklyOffPolicy: '-',
    leavePlan: '-',
    holidayCalendar: '-',
    attendanceNumber: '-',
    payrollTimeSource: '-',
    disableAttendanceTracking: false,
    attendanceCaptureScheme: '-',
    attendancePenalisationPolicy: '-',
    attendanceTrackingPolicy: '-',
    shiftWeeklyOffRule: '-',
    shiftAllowancePolicy: '-',
    overtime: '-',
  },
  customFields: [],
});
