import {
  BarChart3,
  Bell,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ClipboardList,
  Clock3,
  LayoutDashboard,
  ReceiptText,
  Settings,
  UsersRound,
  WalletCards,
  type LucideIcon,
} from 'lucide-react';

import { NAV_LABELS } from '../constants/uiText';

export type NavigationSectionKey = 'organization' | 'workplace' | 'payroll' | 'hr' | 'admin';
export type SidebarPlacement = 'primary' | 'section';

export interface NavigationDestination {
  path: string;
  label: string;
  keywords: readonly string[];
  icon?: LucideIcon;
  section?: NavigationSectionKey;
  sidebar?: SidebarPlacement;
  order: number;
}

export interface NavigationSection {
  key: NavigationSectionKey;
  label: string;
  basePath: string;
  icon: LucideIcon;
  order: number;
}

export const NAVIGATION_SECTIONS: readonly NavigationSection[] = [
  {
    key: 'organization',
    label: NAV_LABELS.organization,
    basePath: '/organization',
    icon: Building2,
    order: 1,
  },
  {
    key: 'workplace',
    label: NAV_LABELS.workplace,
    basePath: '/workplace',
    icon: BriefcaseBusiness,
    order: 2,
  },
  { key: 'payroll', label: NAV_LABELS.payroll, basePath: '/payroll', icon: WalletCards, order: 3 },
  { key: 'hr', label: NAV_LABELS.hr, basePath: '/hr', icon: UsersRound, order: 4 },
  { key: 'admin', label: NAV_LABELS.admin, basePath: '/admin', icon: Settings, order: 5 },
];

export const NAVIGATION_DESTINATIONS: readonly NavigationDestination[] = [
  {
    path: '/insights',
    label: NAV_LABELS.insights,
    keywords: [
      'analytics',
      'reports',
      'workforce',
      'charts',
      'data',
      'metrics',
      'hr insights',
      'ai',
    ],
    icon: BarChart3,
    sidebar: 'primary',
    order: 10,
  },
  {
    path: '/dashboard',
    label: NAV_LABELS.dashboard,
    keywords: ['home', 'start', 'overview'],
    icon: LayoutDashboard,
    sidebar: 'primary',
    order: 20,
  },
  {
    path: '/attendance',
    label: NAV_LABELS.attendance,
    keywords: ['time', 'punch', 'clock', 'swipe', 'present', 'location', 'regularize'],
    icon: Clock3,
    sidebar: 'primary',
    order: 30,
  },
  {
    path: '/timesheet',
    label: NAV_LABELS.timesheet,
    keywords: ['hours', 'project', 'weekly', 'submit', 'approve', 'csv', 'billing'],
    icon: ClipboardList,
    sidebar: 'primary',
    order: 40,
  },
  {
    path: '/leave',
    label: NAV_LABELS.leave,
    keywords: ['holiday', 'pto', 'vacation', 'time off', 'absence', 'calendar'],
    icon: CalendarDays,
    sidebar: 'primary',
    order: 50,
  },
  {
    path: '/expenses',
    label: NAV_LABELS.expensesTravel,
    keywords: ['reimbursement', 'claim', 'travel', 'bills', 'tickets'],
    icon: ReceiptText,
    sidebar: 'primary',
    order: 60,
  },
  {
    path: '/notifications',
    label: NAV_LABELS.notifications,
    keywords: ['alerts', 'inbox', 'messages', 'reminders'],
    icon: Bell,
    sidebar: 'primary',
    order: 70,
  },
  {
    path: '/leave/holidays',
    label: NAV_LABELS.leaveCompanyHolidays,
    keywords: ['public holiday', 'bank holiday', 'calendar year', 'all holidays'],
    order: 80,
  },
  {
    path: '/leave/team-calendar',
    label: NAV_LABELS.leaveTeamCalendar,
    keywords: ['who is off', 'leave grid', 'team absence', 'month view'],
    order: 90,
  },
  {
    path: '/profile/settings',
    label: NAV_LABELS.profileSettings,
    keywords: ['account', 'preferences', 'me', 'password', 'my profile'],
    order: 100,
  },
  {
    path: '/organization/employees',
    label: NAV_LABELS.employees,
    keywords: ['directory', 'roster', 'staff', 'colleagues', 'team', 'org'],
    section: 'organization',
    sidebar: 'section',
    order: 110,
  },
  {
    path: '/organization/org-chart',
    label: NAV_LABELS.orgChart,
    keywords: ['hierarchy', 'reporting', 'manager', 'tree', 'structure'],
    section: 'organization',
    sidebar: 'section',
    order: 120,
  },
  {
    path: '/organization/documents',
    label: NAV_LABELS.documents,
    keywords: ['policies', 'handbook', 'files', 'hr documents'],
    section: 'organization',
    sidebar: 'section',
    order: 130,
  },
  {
    path: '/organization/profile-reviews',
    label: 'Profile Reviews',
    keywords: ['hr', 'approval', 'profile change', 'identity', 'bank'],
    section: 'organization',
    sidebar: 'section',
    order: 140,
  },
  {
    path: '/workplace/benefits',
    label: NAV_LABELS.benefits,
    keywords: ['insurance', 'health', 'plans', 'perks'],
    section: 'workplace',
    sidebar: 'section',
    order: 150,
  },
  {
    path: '/workplace/recruitment',
    label: NAV_LABELS.recruitment,
    keywords: ['hiring', 'jobs', 'candidates', 'applications', 'careers'],
    section: 'workplace',
    sidebar: 'section',
    order: 160,
  },
  {
    path: '/workplace/onboarding',
    label: NAV_LABELS.onboardingExit,
    keywords: [
      'joining',
      'checklist',
      'offboarding',
      'resignation',
      'separation',
      'fnf',
      'full and final',
      'clearance',
      'settlement',
      'exit',
    ],
    section: 'workplace',
    sidebar: 'section',
    order: 170,
  },
  {
    path: '/workplace/workflows',
    label: NAV_LABELS.workflows,
    keywords: ['approvals', 'routing', 'leave approval', 'process'],
    section: 'workplace',
    sidebar: 'section',
    order: 180,
  },
  {
    path: '/workplace/performance',
    label: NAV_LABELS.performance,
    keywords: ['goals', 'reviews', 'okr', 'appraisal', '1:1'],
    section: 'workplace',
    sidebar: 'section',
    order: 190,
  },
  {
    path: '/workplace/succession',
    label: NAV_LABELS.succession,
    keywords: ['talent', 'pipeline', 'bench', 'competency'],
    section: 'workplace',
    sidebar: 'section',
    order: 200,
  },
  {
    path: '/workplace/compensation',
    label: NAV_LABELS.compensation,
    keywords: ['bands', 'grade', 'salary structure', 'review cycle'],
    section: 'workplace',
    sidebar: 'section',
    order: 210,
  },
  {
    path: '/workplace/learning',
    label: NAV_LABELS.learning,
    keywords: ['lms', 'courses', 'training', 'skills', 'education'],
    section: 'workplace',
    sidebar: 'section',
    order: 220,
  },
  {
    path: '/workplace/assets',
    label: NAV_LABELS.assets,
    keywords: ['laptop', 'equipment', 'inventory', 'it'],
    section: 'workplace',
    sidebar: 'section',
    order: 230,
  },
  {
    path: '/workplace/grievance',
    label: NAV_LABELS.grievance,
    keywords: [
      'complaint',
      'harassment',
      'hr case',
      'help',
      'support',
      'ethics',
      'posh',
      'concern',
      'issue',
      'report',
      'chat',
      'escalation',
    ],
    section: 'workplace',
    sidebar: 'section',
    order: 240,
  },
  {
    path: '/payroll/payslips',
    label: NAV_LABELS.payrollProcessing,
    keywords: ['salary', 'pay run', 'payroll cycle', 'statutory export', 'paysheet'],
    section: 'payroll',
    sidebar: 'section',
    order: 250,
  },
  {
    path: '/payroll/compensation',
    label: NAV_LABELS.compensationSetup,
    keywords: ['monthly salary', 'employment history', 'gross base', 'ctc', 'hr payroll', 'annual'],
    section: 'payroll',
    sidebar: 'section',
    order: 260,
  },
  {
    path: '/payroll/pay',
    label: NAV_LABELS.incomeTaxSelf,
    keywords: ['declaration', 'proof upload', 'deductions', 'regime', 'old regime', 'new regime'],
    section: 'payroll',
    sidebar: 'section',
    order: 270,
  },
  {
    path: '/payroll/tax',
    label: NAV_LABELS.taxAdmin,
    keywords: ['tax slabs', 'tax configuration', 'tds approval', 'hr tax tools'],
    section: 'payroll',
    sidebar: 'section',
    order: 280,
  },
  {
    path: '/hr',
    label: NAV_LABELS.overview,
    keywords: ['human resources', 'hr home', 'people ops'],
    section: 'hr',
    sidebar: 'section',
    order: 290,
  },
  {
    path: '/hr/people',
    label: NAV_LABELS.peopleAdmin,
    keywords: ['employees', 'roster', 'directory', 'bulk import', 'hr employees'],
    section: 'hr',
    sidebar: 'section',
    order: 300,
  },
  {
    path: '/hr/leaves',
    label: NAV_LABELS.leaveApprovals,
    keywords: ['pending leave', 'approve leave', 'reject', 'queue', 'inbox'],
    section: 'hr',
    sidebar: 'section',
    order: 310,
  },
  {
    path: '/hr/timesheets',
    label: NAV_LABELS.timesheetApprovals,
    keywords: ['weekly hours', 'approve timesheet', 'reject timesheet', 'pending timesheet'],
    section: 'hr',
    sidebar: 'section',
    order: 320,
  },
  {
    path: '/hr/timesheet-assignments',
    label: NAV_LABELS.timesheetProjectAccess,
    keywords: ['project whitelist', 'timesheet projects', 'assign projects', 'hours'],
    section: 'hr',
    sidebar: 'section',
    order: 330,
  },
  {
    path: '/admin/employees',
    label: NAV_LABELS.employees,
    keywords: ['manage users', 'bulk', 'import', 'org admin', 'data'],
    section: 'admin',
    sidebar: 'section',
    order: 340,
  },
  {
    path: '/admin/attendance-policy',
    label: NAV_LABELS.attendancePolicy,
    keywords: ['policy', 'shifts', 'rules', 'geo'],
    section: 'admin',
    sidebar: 'section',
    order: 350,
  },
  {
    path: '/admin/timesheet-settings',
    label: NAV_LABELS.timesheetSettings,
    keywords: ['projects', 'tasks', 'lock policy', 'editable weeks', 'adjustment window'],
    section: 'admin',
    sidebar: 'section',
    order: 360,
  },
  {
    path: '/admin/leave-settings',
    label: NAV_LABELS.leaveSettings,
    keywords: [
      'leave types',
      'policies',
      'balances',
      'holidays',
      'calendar',
      'pto config',
      'hr leave',
      'leave policy',
      'provision',
    ],
    section: 'admin',
    sidebar: 'section',
    order: 370,
  },
  {
    path: '/admin/expense-categories',
    label: NAV_LABELS.expenseCategories,
    keywords: [
      'travel expense',
      'meal allowance',
      'claim types',
      'expense category',
      'expense policy',
      'caps',
      'receipt rule',
      'expense type',
      'reimbursement',
    ],
    section: 'admin',
    sidebar: 'section',
    order: 380,
  },
  {
    path: '/admin/notifications',
    label: NAV_LABELS.notifications,
    keywords: ['announcements', 'direct notifications', 'employee messages', 'publish'],
    section: 'admin',
    sidebar: 'section',
    order: 390,
  },
  {
    path: '/admin/reports',
    label: NAV_LABELS.reports,
    keywords: ['export', 'compliance', 'hr reports'],
    section: 'admin',
    sidebar: 'section',
    order: 400,
  },
  {
    path: '/admin/access',
    label: NAV_LABELS.rolesPermissions,
    keywords: ['rbac', 'roles', 'permissions', 'access matrix', 'security', 'scopes'],
    section: 'admin',
    sidebar: 'section',
    order: 410,
  },
  {
    path: '/admin/module-health',
    label: NAV_LABELS.serviceHealth,
    keywords: ['status', 'services', 'graphql', 'api', 'availability'],
    section: 'admin',
    sidebar: 'section',
    order: 420,
  },
  {
    path: '/admin/settings',
    label: NAV_LABELS.settings,
    keywords: ['tenant', 'configuration', 'roles'],
    section: 'admin',
    sidebar: 'section',
    order: 430,
  },
];
