import { Laptop, MessageSquareWarning } from 'lucide-react';

import type { NavigationDestination } from './navigationModel';

/** Existing workplace routes grouped by business function. URLs remain compatible. */
export const WORKPLACE_DESTINATIONS: readonly NavigationDestination[] = [
  {
    path: '/workplace/compensation',
    label: 'Salary Bands & Reviews',
    section: 'payroll',
    sidebar: 'section',
    order: 74,
    keywords: ['compensation', 'bands', 'grade', 'review cycle', 'budget'],
  },
  {
    path: '/workplace/benefits',
    label: 'Benefits',
    section: 'payroll',
    sidebar: 'section',
    order: 75,
    keywords: ['insurance', 'health', 'plans', 'perks', 'enrollment'],
  },
  {
    path: '/workplace/recruitment',
    label: 'Recruitment',
    section: 'hiring',
    sidebar: 'section',
    order: 81,
    keywords: ['hiring', 'jobs', 'candidates', 'applications', 'careers'],
  },
  {
    path: '/workplace/prejoining',
    label: 'Pre-joining',
    section: 'hiring',
    sidebar: 'section',
    order: 82,
    keywords: ['candidate', 'invitation', 'new hire', 'documents', 'joining', 'review'],
  },
  {
    path: '/workplace/onboarding',
    label: 'Onboarding & Exit',
    section: 'hiring',
    sidebar: 'section',
    order: 83,
    keywords: [
      'joining',
      'checklist',
      'offboarding',
      'resignation',
      'separation',
      'fnf',
      'clearance',
      'settlement',
    ],
  },
  {
    path: '/workplace/learning',
    label: 'Learning',
    section: 'talent',
    sidebar: 'section',
    order: 91,
    keywords: ['lms', 'courses', 'training', 'skills', 'education'],
  },
  {
    path: '/workplace/succession',
    label: 'Succession Planning',
    section: 'talent',
    sidebar: 'section',
    order: 92,
    keywords: ['talent', 'pipeline', 'bench', 'competency'],
  },
  {
    path: '/workplace/surveys',
    label: 'Surveys',
    section: 'engagement',
    sidebar: 'section',
    order: 101,
    keywords: ['survey', 'pulse', 'engagement', 'feedback', 'comments'],
  },
  {
    path: '/workplace/assets',
    label: 'Assets',
    sidebar: 'primary',
    icon: Laptop,
    order: 110,
    keywords: ['laptop', 'equipment', 'inventory', 'it'],
  },
  {
    path: '/workplace/grievance',
    label: 'Grievance & Speak Up',
    sidebar: 'primary',
    icon: MessageSquareWarning,
    order: 120,
    keywords: [
      'complaint',
      'harassment',
      'help',
      'support',
      'ethics',
      'posh',
      'concern',
      'issue',
      'escalation',
    ],
  },
];
