import { NAV_LABELS } from '../constants/uiText';

import type { NavigationDestination } from './navigationModel';

export const WORKPLACE_DESTINATIONS: readonly NavigationDestination[] = [
  {
    path: '/workplace/benefits',
    label: NAV_LABELS.benefits,
    keywords: ['insurance', 'health', 'plans', 'perks'],
    section: 'workplace',
    sidebar: 'section',
    order: 150,
  },
  {
    path: '/workplace/recruitment',
    label: NAV_LABELS.recruitment,
    keywords: ['hiring', 'jobs', 'candidates', 'applications', 'careers'],
    section: 'workplace',
    sidebar: 'section',
    order: 160,
  },
  {
    path: '/workplace/prejoining',
    label: 'Pre-joining',
    keywords: ['candidate', 'invitation', 'new hire', 'documents', 'joining', 'review'],
    section: 'workplace',
    sidebar: 'section',
    order: 165,
  },
  {
    path: '/workplace/onboarding',
    label: NAV_LABELS.onboardingExit,
    keywords: [
      'joining',
      'checklist',
      'offboarding',
      'resignation',
      'separation',
      'fnf',
      'full and final',
      'clearance',
      'settlement',
      'exit',
    ],
    section: 'workplace',
    sidebar: 'section',
    order: 170,
  },
  {
    path: '/workplace/workflows',
    label: NAV_LABELS.workflows,
    keywords: ['approvals', 'routing', 'leave approval', 'process'],
    section: 'workplace',
    sidebar: 'section',
    order: 180,
  },
  {
    path: '/workplace/performance',
    label: NAV_LABELS.performance,
    keywords: ['goals', 'reviews', 'okr', 'appraisal', '1:1'],
    section: 'workplace',
    sidebar: 'section',
    order: 190,
  },
  {
    path: '/workplace/surveys',
    label: NAV_LABELS.surveys,
    keywords: ['survey', 'pulse', 'engagement', 'feedback', 'comments'],
    section: 'workplace',
    sidebar: 'section',
    order: 195,
  },
  {
    path: '/workplace/succession',
    label: NAV_LABELS.succession,
    keywords: ['talent', 'pipeline', 'bench', 'competency'],
    section: 'workplace',
    sidebar: 'section',
    order: 200,
  },
  {
    path: '/workplace/compensation',
    label: NAV_LABELS.compensation,
    keywords: ['bands', 'grade', 'salary structure', 'review cycle'],
    section: 'workplace',
    sidebar: 'section',
    order: 210,
  },
  {
    path: '/workplace/learning',
    label: NAV_LABELS.learning,
    keywords: ['lms', 'courses', 'training', 'skills', 'education'],
    section: 'workplace',
    sidebar: 'section',
    order: 220,
  },
  {
    path: '/workplace/assets',
    label: NAV_LABELS.assets,
    keywords: ['laptop', 'equipment', 'inventory', 'it'],
    section: 'workplace',
    sidebar: 'section',
    order: 230,
  },
  {
    path: '/workplace/grievance',
    label: NAV_LABELS.grievance,
    keywords: [
      'complaint',
      'harassment',
      'hr case',
      'help',
      'support',
      'ethics',
      'posh',
      'concern',
      'issue',
      'report',
      'chat',
      'escalation',
    ],
    section: 'workplace',
    sidebar: 'section',
    order: 240,
  },
];
